{
 "title": "OpenStack-Health-Monitor2",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "mycmd", "label": "cmd", "query": "show tag values with key = cmd" },
   {
    "name": "mymethod",
    "label": "method",
    "query": "show tag values with key = method where cmd =~ /$mycmd/"
   },
   { "name": "mywait", "label": "Resrc", "query": "show tag values with key = cmd" },
   { "name": "mybench", "label": "Bench", "query": "show tag values with key = cmd" }
  ]
 },
 "panels": [
  {
   "title": "API calls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gx-scs",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "API errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "gx-scs",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "API success rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "API falis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "gx-scs",
     "query": "SELECT ((count(\"return_code\")-sum(\"return_code\"))/count(\"return_code\")) FROM \"gx-scs\" WHERE (\"cmd\" =~ /^$mycmd$/ AND \"method\" =~ /^$mymethod$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "ssh conns",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gx-scs",
     "query": "SELECT count(\"return_code\") FROM \"gx-scs\" WHERE (\"cmd\" = ssh) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=", "value": "ssh" }
     ]
    }
   ]
  },
  {
   "title": "ssh errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "gx-scs",
     "query": "SELECT sum(\"return_code\") FROM \"gx-scs\" WHERE (\"cmd\" = ssh) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=", "value": "ssh" }
     ]
    }
   ]
  },
  {
   "title": "ssh success rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "API falis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "gx-scs",
     "query": "SELECT ((count(\"return_code\")-sum(\"return_code\"))/count(\"return_code\")) FROM \"gx-scs\" WHERE (\"cmd\" = ssh) AND $timeFilter",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "Resrcs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gx-scs",
     "query": "SELECT count(\"return_code\") FROM \"gx-scs\" WHERE (\"cmd\" = ssh) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mywait$/" }
     ]
    }
   ]
  },
  {
   "title": "Resrc errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "gx-scs",
     "query": "SELECT sum(\"return_code\") FROM \"gx-scs\" WHERE (\"cmd\" = ssh) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mywait$/" }
     ]
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "API errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "rc" }
   ],
   "targets": [
    {
     "alias": "$tag_cmd $tag_method",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" }
     ],
     "measurement": "gx-scs",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "API response times",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_cmd $tag_method",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gx-scs",
     "query": "SELECT \"duration\" FROM \"gx-scs\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "Resource wait",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_cmd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gx-scs",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mywait$/" }
     ]
    }
   ]
  },
  {
   "title": "Bench",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "s, Gb/s" }
   ],
   "targets": [
    {
     "alias": "$tag_cmd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gx-scs",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mybench$/" }
     ]
    }
   ]
  },
  {
   "title": "Bench (ssh) errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Errs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gx-scs",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mybench$/" }
     ]
    }
   ]
  }
 ]
}