---
name: Build docker image

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - "*.sh"
      - .github/workflows/build-docker-image.yml
      - Dockerfile
      - files/**
  pull_request:
    paths:
      - "*.sh"
      - .github/workflows/build-docker-image.yml
      - Dockerfile
      - files/**

jobs:

  build-docker-image:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'
      - run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: sovereigncloudstack/openstack-health-monitor
      - run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: sovereigncloudstack/openstack-health-monitor
        if: github.ref == 'refs/heads/master'
