---
name: Check docker syntax

"on":
  push:
    paths:
      - Dockerfile
      - .github/workflows/check-docker-syntax.yml
    branches:
      - master
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/check-docker-syntax.yml

jobs:
  check-docker-syntax:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-hadolint@v1.6.0
        with:
          dockerfile: Containerfile
          recursive: true
